services:
  app:
    build:
      context: .
      args:
        # Comment out the next line to prevent installing nodemon.
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    image: node-utility-container
    # Using a heredoc to create a multi-line command.
    command: npm run dev
