
## 
# Run the following command to create an image and
# initialize a project in this directory
#
#   docker compose -f docker-compose-initialization.yaml up --build
#
##
services:
  app:
    build: .
    volumes:
      - .:/app/  # This will be created on the host machine if it doesn't exist.
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    image: node-utility-container
    # Using a heredoc to create a multi-line command.
    # "start": "node src/app.js",
    # "dev": "node node_modules/nodemon/bin/nodemon.js src/app.js"
    command: npm run dev
